[mcp_servers.filesystem]
command = "cmd"
args = [
    "/c",
    "npx",
    "-y",
    "@modelcontextprotocol/server-filesystem",
    'e:\97-codes\torch_parallel\llm-knowledge\wiki',
    'e:\97-codes\torch_parallel\llm-knowledge\raw',
]

[mcp_servers.qmd]
command = "cmd"
args = [
    "/c",
    "node",
    'C:\Users\suhaibo\AppData\Roaming\npm\node_modules\@tobilu\qmd\dist\cli\qmd.js',
    "mcp",
]
