// Analytical storage ledger, not a Megatron allocator or PP simulator.
// Figure spec: three same-scale panels k=1/2/4. Four ordered event columns:
// end of original forwards -> first segment replay -> its backward -> all consumed.
// Gray = retained boundaries, orange = replay internals; blue outline = model peak.
// Every height/count is generated by unique-storage allocate/free events.
import { pathToFileURL } from 'node:url';

const MiB = 2 ** 20;
export function ledger({ b=1, s=2048, h=4096, a=32, f=16384, bytes=2 }={}) {
  for (const v of [b,s,h,a,f,bytes]) if (!Number.isInteger(v) || v<1) throw Error('positive integer dimensions required');
  if (h%a) throw Error('hidden size must divide into heads');
  const boundary=b*s*h*bytes;
  const tensors={ X:boundary,U:boundary,QKV:3*boundary,P:b*a*s*s*bytes,C:boundary,R:boundary,Vm:boundary,A:b*s*f*bytes,B:b*s*f*bytes };
  const layer=Object.values(tensors).reduce((a,b)=>a+b,0);
  return {tensors,boundary,layer,internal:layer-boundary};
}

export function simulate({layers=24,pending=4,group=1,account=ledger()}={}) {
  for(const v of [layers,pending,group]) if(!Number.isInteger(v)||v<1) throw Error('positive integer schedule required');
  const segments=[];
  for(let start=0;start<layers;start+=group) segments.push({start,end:Math.min(start+group,layers)});
  const live=new Map(), events=[];
  const add=(id,bytes,kind)=>{if(live.has(id))throw Error('duplicate storage');live.set(id,{bytes,kind});};
  const remove=id=>{if(!live.delete(id))throw Error(`missing storage ${id}`);};
  const record=phase=>{
    let saved=0,replay=0;
    for(const v of live.values()) {if(v.kind==='saved') saved+=v.bytes; else replay+=v.bytes;}
    events.push({phase,saved,replay,total:saved+replay,count:live.size});
  };
  for(let m=0;m<pending;m++) for(const seg of segments) add(`${m}:x:${seg.start}`,account.boundary,'saved');
  record('forward-end');
  for(let m=pending-1;m>=0;m--) for(const seg of segments.toReversed()) {
    for(let l=seg.start;l<seg.end;l++) {
      if(l!==seg.start) add(`${m}:x:${l}`,account.boundary,'replay');
      add(`${m}:i:${l}`,account.internal,'replay');
      record('replay-layer');
    }
    // Replay produces a fresh segment output; it does not alias the original
    // forward boundary saved by the next checkpoint. Nested backward holds it.
    add(`${m}:out:${seg.start}`,account.boundary,'replay');
    record('segment-replayed');
    for(let l=seg.end-1;l>=seg.start;l--) {
      remove(`${m}:i:${l}`);
      if(l!==seg.start) remove(`${m}:x:${l}`);
      record('backward-layer');
    }
    remove(`${m}:out:${seg.start}`);
    remove(`${m}:x:${seg.start}`);
    record('segment-consumed');
  }
  record('all-consumed');
  return {segments,events,peak:Math.max(...events.map(e=>e.total)),initial:events[0].total};
}

export function comparison(account=ledger(),layers=24) {
  const H=account.boundary,A=account.layer,T=account.tensors;
  return [
    ['不重算',layers*A],['full uniform k=1',layers*H],
    ['full uniform k=4',Math.ceil(layers/4)*H],
    ['full block n=12',Math.min(12,layers)*H+Math.max(0,layers-12)*A],
    ['selective core_attn',layers*(A-T.P)],
    ['selective mlp',layers*(A-T.A-T.B)],
    ['selective layernorm（CWO）',layers*(A-T.U-T.Vm)],
  ].map(([name,saved])=>({name,saved,saving:layers*A-saved}));
}

// Same declared window as simulate(). No activation gradients or temporary
// kernels are counted. Listed saved tensors die after their last consumer.
export function simulateChoice({strategy='none',selected=12,layers=24,pending=4,account=ledger()}={}) {
  if(!['none','block','core'].includes(strategy)) throw Error('unknown strategy');
  for(const v of [layers,pending]) if(!Number.isInteger(v)||v<1) throw Error('invalid window');
  if(strategy==='block'&&(!Number.isInteger(selected)||selected<0||selected>layers)) throw Error('invalid block count');
  const live=new Map(),events=[];
  const add=(id,bytes,kind='saved')=>{if(live.has(id))throw Error('duplicate storage');live.set(id,{bytes,kind});};
  const remove=id=>{if(!live.delete(id))throw Error(`missing ${id}`);};
  const record=phase=>{
    let saved=0,replay=0;
    for(const v of live.values())if(v.kind==='saved')saved+=v.bytes;else replay+=v.bytes;
    events.push({phase,saved,replay,total:saved+replay,count:live.size});
  };
  const names=(l)=>strategy==='block'&&l<selected?['X']:Object.keys(account.tensors).filter(k=>strategy!=='core'||k!=='P');
  for(let m=0;m<pending;m++)for(let l=0;l<layers;l++)for(const k of names(l))add(`${m}:${l}:${k}`,account.tensors[k]);
  record('forward-end');
  for(let m=pending-1;m>=0;m--)for(let l=layers-1;l>=0;l--){
    const key=k=>`${m}:${l}:${k}`;
    if(strategy==='block'&&l<selected){
      add(key('replay'),account.internal+account.boundary,'replay');record('layer-replayed');
      remove(key('replay'));remove(key('X'));record('layer-consumed');
    }else if(strategy==='core'){
      // FC2 -> activation -> FC1 -> norm2 -> attention output projection.
      for(const k of ['B','A','Vm','R','C']){remove(key(k));record(`consumer-${k}`);}
      // Fresh checkpoint output is held for nested backward; old C is gone.
      add(key('new-P'),account.tensors.P,'replay');
      add(key('new-C'),account.tensors.C,'replay');record('core-replayed');
      remove(key('new-P'));remove(key('new-C'));
      for(const k of ['QKV','U','X'])remove(key(k));record('layer-consumed');
    }else{
      for(const k of names(l))remove(key(k));record('layer-consumed');
    }
  }
  return {events,initial:events[0].total,peak:Math.max(...events.map(x=>x.total))};
}

export function choiceModels(){
  return [
    {name:'不重算',work:'0',...simulateChoice()},
    {name:'core_attn',work:'24 / 13 F',...simulateChoice({strategy:'core'})},
    {name:'block n=12',work:'12 F',...simulateChoice({strategy:'block'})},
    {name:'block n=15',work:'15 F',...simulateChoice({strategy:'block',selected:15})},
    {name:'uniform k=2',work:'24 F',...simulate({group:2})},
  ];
}

export function mlaExample({tokens=4,heads=2,qRank=2,kvRank=2,key=2,rope=2,value=2,bytes=2}={}){
  return {
    retained:tokens*(qRank+kvRank+rope)*bytes,
    query:tokens*heads*(key+rope)*bytes,
    key:tokens*heads*(key+rope)*bytes,
    value:tokens*heads*value*bytes,
    replayFlops:2*tokens*(qRank*heads*(key+rope)+kvRank*heads*(key+value)),
  };
}

export function renderChoices(){
  // Figure spec: one common 0..48 GiB axis compares the same pending window.
  // Gray shows post-forward retention; orange marks the event-derived peak.
  // Last-consumer release explains the core/block difference; work is separate
  // from capacity and explicitly measured in layer-forward FLOPs, not seconds.
  const rows=choiceModels(),gib=2**30,scale=530/48;
  const out=[`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 570" role="img" aria-label="同一在途窗口下的重计算方案、峰值与额外工作">
<style>text{font:14px 'Microsoft YaHei','Segoe UI',sans-serif;fill:#344054}.title{font-size:21px;font-weight:700}.small{font-size:12px}.peak{fill:#c3651f}</style>
<rect width="1100" height="570" fill="white"/>
<text class="title" x="24" y="34">先看何时释放，再比较容量预算</text>
<text x="24" y="62">L=24，w=4；先完成四份前向，再逆序反向。F 为一层前向矩阵乘工作，不是时间。</text>
<text x="24" y="94">方案</text><text x="200" y="94">灰条：原前向后留存　橙线：事件峰值（GiB）</text>
<text x="815" y="94">留存 → 峰值</text><text x="976" y="94">额外工作 / 份</text>`];
  rows.forEach((r,i)=>{
    const y=119+i*56,v=r.initial/gib,p=r.peak/gib,x=200;
    out.push(`<text x="24" y="${y+19}">${r.name}</text><rect x="${x}" y="${y}" width="${v*scale}" height="28" fill="#e4e7ec"/>
<line x1="${x+p*scale}" x2="${x+p*scale}" y1="${y-4}" y2="${y+32}" stroke="#c3651f" stroke-width="3"/>
<text x="815" y="${y+19}">${v} → ${p}</text><text x="976" y="${y+19}">${r.work}</text>`);
  });
  out.push(`<text class="small" x="200" y="420">0</text><text class="small" x="720" y="420">48 GiB</text>
<text x="24" y="452">block：未重算尾层先释放；首层回放时，不能再加上已经消费的尾层。</text>
<text x="24" y="479">core：先释放 B/A/Vₘ/R/C 共 176 MiB，再重建 P 与新 C 共 272 MiB；首次峰值比留存多 96 MiB。</text>
<text x="24" y="506">uniform：原留存很小，但一次重建两层；峰值出现在嵌套反向消费之前。</text>
<text class="small" x="24" y="542">解析生命周期模型；释放点按最后消费者约定。未计项与其它保留引用会改变实际 GPU 峰值，必须测量。</text></svg>`);
  return out.join('\n');
}

export function render() {
  const groups=[1,2,4],models=groups.map(group=>simulate({group}));
  const max=2600,base=385,scale=260/max;
  const out=[`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 560" role="img" aria-label="uniform 保存边界与回放激活的容量变化：k 等于 ${groups.join('、')} 的模型峰值为 ${models.map(m=>m.peak/MiB).join('、')} MiB">
<style>text{font:12px 'Microsoft YaHei','Segoe UI',sans-serif;fill:#344054}.title{font-size:20px;font-weight:700}.heading{font-size:16px;font-weight:700}.small{font-size:11px}.grid{stroke:#e5e7eb}.saved{fill:#e4e7ec;stroke:#98a2b3}.replay{fill:#fff0dd;stroke:#c3651f}.peak{fill:none;stroke:#2563eb;stroke-width:2}.blue{fill:#2563eb}</style>
<rect width="1100" height="560" fill="white"/>
<text class="title" x="24" y="30">检查点更少，回放峰值却可能更高</text>
<text x="24" y="54">同一教学账本：L=24，w=4，层输入 H=16 MiB，内部 I=496 MiB；仅统计已列激活存储。</text>
<rect class="saved" x="24" y="72" width="18" height="12"/><text x="49" y="83">保留的组首输入</text>
<rect class="replay" x="198" y="72" width="18" height="12"/><text x="223" y="83">回放内部、组内输入及新输出</text>
<text class="blue" x="499" y="83">蓝框：本模型峰值时刻</text>`];
  groups.forEach((k,i)=>{
    const m=models[i],left=56+i*355;
    const points=[m.events[0],m.events.find(e=>e.phase==='segment-replayed'),m.events.find(e=>e.phase==='segment-consumed'),m.events.at(-1)];
    const names=['原前向结束','首组回放后','首组反向后','全部消费'];
    out.push(`<text class="heading" x="${left}" y="113">k=${k}：${m.segments.length} 组 / microbatch</text>`);
    for(const value of [0,1000,2000]) {
      const y=base-value*scale;
      out.push(`<line class="grid" x1="${left-5}" y1="${y}" x2="${left+284}" y2="${y}"/><text class="small" text-anchor="end" x="${left-10}" y="${y+4}">${value}</text>`);
    }
    points.forEach((p,j)=>{
      const x=left+j*73,sh=p.saved/MiB*scale,rh=p.replay/MiB*scale;
      out.push(`<rect class="saved" x="${x}" y="${base-sh}" width="47" height="${sh}"/>
<rect class="replay" x="${x}" y="${base-sh-rh}" width="47" height="${rh}"/>
<text text-anchor="middle" x="${x+23.5}" y="${base-sh-rh-8}">${p.total/MiB}</text>
<text class="small" text-anchor="middle" x="${x+23.5}" y="410">${names[j]}</text>`);
      if(p.total===m.peak) out.push(`<rect class="peak" x="${x-3}" y="${base-sh-rh-3}" width="53" height="${sh+rh+6}"/>`);
    });
    out.push(`<text x="${left}" y="440">首次回放新增：${points[1].replay/MiB} MiB</text>
<text class="blue" x="${left}" y="462">模型峰值：${m.peak/MiB} MiB</text>`);
  });
  out.push(`<text x="24" y="498">纵轴：MiB；横轴：事件先后，不表示等长时间。先保留四份前向，再串行回放并反向消费至零。</text>
<text x="24" y="522">k 增大：边界更少，但一次重建的层更多。组首输入不重复计入；回放新输出另占 H。</text>
<text class="small" x="24" y="545">不含模型状态、激活梯度、算子/通信缓冲及 allocator 容量；真实峰值需按实际 PP/VPP 时间线测量。</text></svg>`);
  return out.join('\n');
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href) console.log(render());
