// Analytical storage ledger, not a Megatron allocator or PP simulator.
// Figure spec: three same-scale panels k=1/2/4. Four ordered event columns:
// end of original forwards -> first segment replay -> its backward -> all consumed.
// Gray = retained boundaries, orange = replay internals; blue outline = model peak.
// Every height/count is generated by unique-storage allocate/free events.
import { pathToFileURL } from 'node:url';

const MiB = 2 ** 20;
export function ledger({ b=1, s=2048, h=4096, a=32, f=16384, bytes=2 }={}) {
  for (const v of [b,s,h,a,f,bytes]) if (!Number.isInteger(v) || v<1) throw Error('positive integer dimensions required');
  if (h%a) throw Error('hidden size must divide into heads');
  const boundary=b*s*h*bytes;
  const tensors={ X:boundary,U:boundary,QKV:3*boundary,P:b*a*s*s*bytes,C:boundary,R:boundary,Vm:boundary,A:b*s*f*bytes,B:b*s*f*bytes };
  const layer=Object.values(tensors).reduce((a,b)=>a+b,0);
  return {tensors,boundary,layer,internal:layer-boundary};
}

export function simulate({layers=24,pending=4,group=1,account=ledger()}={}) {
  for(const v of [layers,pending,group]) if(!Number.isInteger(v)||v<1) throw Error('positive integer schedule required');
  const segments=[];
  for(let start=0;start<layers;start+=group) segments.push({start,end:Math.min(start+group,layers)});
  const live=new Map(), events=[];
  const add=(id,bytes,kind)=>{if(live.has(id))throw Error('duplicate storage');live.set(id,{bytes,kind});};
  const remove=id=>{if(!live.delete(id))throw Error(`missing storage ${id}`);};
  const record=phase=>{
    let saved=0,replay=0;
    for(const v of live.values()) {if(v.kind==='saved') saved+=v.bytes; else replay+=v.bytes;}
    events.push({phase,saved,replay,total:saved+replay,count:live.size});
  };
  for(let m=0;m<pending;m++) for(const seg of segments) add(`${m}:x:${seg.start}`,account.boundary,'saved');
  record('forward-end');
  for(let m=pending-1;m>=0;m--) for(const seg of segments.toReversed()) {
    for(let l=seg.start;l<seg.end;l++) {
      if(l!==seg.start) add(`${m}:x:${l}`,account.boundary,'replay');
      add(`${m}:i:${l}`,account.internal,'replay');
      record('replay-layer');
    }
    // Replay produces a fresh segment output; it does not alias the original
    // forward boundary saved by the next checkpoint. Nested backward holds it.
    add(`${m}:out:${seg.start}`,account.boundary,'replay');
    record('segment-replayed');
    for(let l=seg.end-1;l>=seg.start;l--) {
      remove(`${m}:i:${l}`);
      if(l!==seg.start) remove(`${m}:x:${l}`);
      record('backward-layer');
    }
    remove(`${m}:out:${seg.start}`);
    remove(`${m}:x:${seg.start}`);
    record('segment-consumed');
  }
  record('all-consumed');
  return {segments,events,peak:Math.max(...events.map(e=>e.total)),initial:events[0].total};
}

export function comparison(account=ledger(),layers=24) {
  const H=account.boundary,A=account.layer,T=account.tensors;
  return [
    ['不重算',layers*A],['full uniform k=1',layers*H],
    ['full uniform k=4',Math.ceil(layers/4)*H],
    ['full block n=12',Math.min(12,layers)*H+Math.max(0,layers-12)*A],
    ['selective core_attn',layers*(A-T.P)],
    ['selective mlp',layers*(A-T.A-T.B)],
    ['selective layernorm（CWO）',layers*(A-T.U-T.Vm)],
  ].map(([name,saved])=>({name,saved,saving:layers*A-saved}));
}

export function render() {
  const groups=[1,2,4],models=groups.map(group=>simulate({group}));
  const max=2600,base=385,scale=260/max;
  const out=[`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 560" role="img" aria-label="uniform 保存边界与回放激活的容量变化：k 等于 ${groups.join('、')} 的模型峰值为 ${models.map(m=>m.peak/MiB).join('、')} MiB">
<style>text{font:12px 'Microsoft YaHei','Segoe UI',sans-serif;fill:#344054}.title{font-size:20px;font-weight:700}.heading{font-size:16px;font-weight:700}.small{font-size:11px}.grid{stroke:#e5e7eb}.saved{fill:#e4e7ec;stroke:#98a2b3}.replay{fill:#fff0dd;stroke:#c3651f}.peak{fill:none;stroke:#2563eb;stroke-width:2}.blue{fill:#2563eb}</style>
<rect width="1100" height="560" fill="white"/>
<text class="title" x="24" y="30">检查点更少，回放峰值却可能更高</text>
<text x="24" y="54">同一教学账本：L=24，w=4，层输入 H=16 MiB，内部 I=496 MiB；仅统计已列激活存储。</text>
<rect class="saved" x="24" y="72" width="18" height="12"/><text x="49" y="83">保留的组首输入</text>
<rect class="replay" x="198" y="72" width="18" height="12"/><text x="223" y="83">回放内部、组内输入及新输出</text>
<text class="blue" x="499" y="83">蓝框：本模型峰值时刻</text>`];
  groups.forEach((k,i)=>{
    const m=models[i],left=56+i*355;
    const points=[m.events[0],m.events.find(e=>e.phase==='segment-replayed'),m.events.find(e=>e.phase==='segment-consumed'),m.events.at(-1)];
    const names=['原前向结束','首组回放后','首组反向后','全部消费'];
    out.push(`<text class="heading" x="${left}" y="113">k=${k}：${m.segments.length} 组 / microbatch</text>`);
    for(const value of [0,1000,2000]) {
      const y=base-value*scale;
      out.push(`<line class="grid" x1="${left-5}" y1="${y}" x2="${left+284}" y2="${y}"/><text class="small" text-anchor="end" x="${left-10}" y="${y+4}">${value}</text>`);
    }
    points.forEach((p,j)=>{
      const x=left+j*73,sh=p.saved/MiB*scale,rh=p.replay/MiB*scale;
      out.push(`<rect class="saved" x="${x}" y="${base-sh}" width="47" height="${sh}"/>
<rect class="replay" x="${x}" y="${base-sh-rh}" width="47" height="${rh}"/>
<text text-anchor="middle" x="${x+23.5}" y="${base-sh-rh-8}">${p.total/MiB}</text>
<text class="small" text-anchor="middle" x="${x+23.5}" y="410">${names[j]}</text>`);
      if(p.total===m.peak) out.push(`<rect class="peak" x="${x-3}" y="${base-sh-rh-3}" width="53" height="${sh+rh+6}"/>`);
    });
    out.push(`<text x="${left}" y="440">首次回放新增：${points[1].replay/MiB} MiB</text>
<text class="blue" x="${left}" y="462">模型峰值：${m.peak/MiB} MiB</text>`);
  });
  out.push(`<text x="24" y="498">纵轴：MiB；横轴：事件先后，不表示等长时间。先保留四份前向，再串行回放并反向消费至零。</text>
<text x="24" y="522">k 增大：边界更少，但一次重建的层更多。组首输入不重复计入；回放新输出另占 H。</text>
<text class="small" x="24" y="545">不含模型状态、激活梯度、算子/通信缓冲及 allocator 容量；真实峰值需按实际 PP/VPP 时间线测量。</text></svg>`);
  return out.join('\n');
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href) console.log(render());
